jobs:
- job:
  displayName: ubuntu-20.04
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION numpy
    displayName: Install Anaconda packages

  - bash: |
      source activate myEnvironment
      pip install pytest pytest-azurepipelines
      pytest
    displayName: pytest

- job:
  displayName: macOS-10.15
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION numpy
      pip install pytest pytest-azurepipelines
    displayName: Install Anaconda packages

  - bash: |
      source activate myEnvironment
      pytest
    displayName: pytest

- job:
  displayName: windows-2019
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python38:
        python.version: '3.8'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - script: |
      call activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=%PYTHON_VERSION% numpy
    displayName: Install Anaconda packages

  - script: |
      call activate myEnvironment
      pip install pytest pytest-azurepipelines
      pytest
    displayName: pytest

- job:
  displayName: From environment.yml
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda env create --quiet --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate env-from-yaml
      pip install pytest pytest-azurepipelines
      pytest
    displayName: pytest
